name: Update Arabic IPTV
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'resources/exclude_words.txt'          # Triggers build when words change
      - '.scripts/process_iptv.py'             # Triggers build when code changes
      - 'resources/logo_map.json'              # Triggers build when code changes
      - 'resources/id_map.json'                # Triggers build when code changes
      - 'resources/logos/**'                   # Triggers build when code changes

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

concurrency:
  group: epg-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run filter script
        run: python .scripts/process_iptv.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Use -A to ensure all new images and the modified m3u/xml are caught
          git add resources/logos/
          git add curated.m3u arabic-epg.xml
          git commit -m "Update logos and EPG: $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || echo "No changes"
          git push origin main
